spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: root
        password: 123456
logging:
  level:
    com.ritian.springboot.mapper: debug
mapper:
  mappers:
   - com.ritian.springboot.util.MyMapper
  not-empty: true
